# Generated by Django 4.1.5 on 2023-01-23 11:06

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('bgColor', models.CharField(max_length=8)),
                ('tintColor', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eventStartDate', models.DateTimeField(auto_now=True)),
                ('eventFinishDate', models.DateTimeField(auto_now=True, null=True)),
                ('bannerVerticalImg', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='EventBannerVerticalImage/')),
                ('bannerHorizontalImg', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='EventBannerHorizontalImage/')),
                ('localization', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('isBanner', models.BooleanField(default=False)),
            ],
        ),
    ]
