# Generated by Django 4.1.5 on 2023-01-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0006_remove_locationmodel_user_usertolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
