# Generated by Django 4.1.5 on 2023-01-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0007_eventmodel_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
