# Generated by Django 4.1.5 on 2023-01-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ticketmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
