# Generated by Django 4.1.5 on 2023-01-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0002_remove_ticketmodel_quantity_remove_ticketmodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
