# Generated by Django 4.1.5 on 2023-01-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0005_orderitemmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='ticket',
        ),
    ]
