# Generated by Django 4.1.5 on 2023-01-23 22:37

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='ArtistProfileImg/')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('instagram', models.URLField(max_length=300)),
                ('spotify', models.URLField(max_length=300)),
                ('facebook', models.URLField(max_length=300)),
            ],
        ),
    ]
