# Generated by Django 4.1.5 on 2023-01-24 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeApp', '0008_eventmodel_slug'),
        ('profileApp', '0003_followedartistsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedEventsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeApp.eventmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
